"""
Morrowind PGRD pathgrids, split onto Oblivion's cell grid.

TES3 and TES4 pathgrids hold the same graph in different encodings: TES3 stores
point positions as S32 and its PGRC edge targets as U32, where TES4 uses floats
and S16. Neither game scales world positions, so a point carries across
unchanged and only the owning cell changes -- one Morrowind cell's grid splits
across the four Oblivion cells it covers, exactly as its references do.

An edge whose two points land in different quadrants cannot stay an edge: TES4
expresses a crossing as a PGRI inter-cell entry naming the local point and the
FOREIGN point's world position, which is what the navmesh corridor builder
stitches cells together with.

See: docs/commentary/tes4_export_morrowind.md#pathgrids
"""

import struct

from .morrowind_world import (TES4_CELL_SIZE, cell_grid,
                              tes3_cell_quadrants)
from .tes3_reader import get_subrecord

#: A Morrowind cell spans two Oblivion cells on each axis.
TES3_CELL_SIZE = TES4_CELL_SIZE * 2

#: TES3 PGRD.DATA: grid X/Y (S32), granularity (U16), point count (U16).
DATA_SIZE = 12

#: TES3 PGRP point: X/Y/Z (S32), autogenerated (U8), connections (U8), pad(2).
POINT_SIZE = 16

#: TES4 stores an edge target as S16, so a wider graph cannot be indexed.
MAX_TES4_POINT = 32767

#: Points a TES4 pathgrid needs before the importer will build a navmesh.
MIN_POINTS = 2


def parse_pathgrid(rec) -> tuple:
    """(grid, points, edges) for one TES3 PGRD, or None when unusable.

    `points` are (x, y, z) world floats and `edges` a set of (lo, hi) index
    pairs; a self-edge or an out-of-range target is dropped as CS garbage.
    """
    data = get_subrecord(rec, 'DATA')
    pgrp = get_subrecord(rec, 'PGRP')
    if data is None or pgrp is None or len(data.data) < DATA_SIZE:
        return None
    grid = struct.unpack_from('<ii', data.data, 0)
    points, degrees = _read_points(pgrp.data)
    if not points:
        return None
    return grid, points, _read_edges(rec, degrees, len(points))


def _read_points(blob: bytes) -> tuple:
    """The (x, y, z) list and the per-point connection count."""
    points, degrees = [], []
    for off in range(0, len(blob) - POINT_SIZE + 1, POINT_SIZE):
        x, y, z = struct.unpack_from('<iii', blob, off)
        points.append((float(x), float(y), float(z)))
        degrees.append(blob[off + 13])
    return points, degrees


def _read_edges(rec, degrees: list, count: int) -> set:
    """Undirected edges from PGRC, a flat U32 run grouped by connection count.

    Stored directed and often asymmetrically -- Morrowind walks an edge from
    either end regardless -- so each pair is normalized to (lo, hi).
    """
    pgrc = get_subrecord(rec, 'PGRC')
    if pgrc is None:
        return set()
    total = len(pgrc.data) // 4
    targets = struct.unpack_from('<%dI' % total, pgrc.data, 0)
    edges, flat = set(), 0
    for source, degree in enumerate(degrees):
        for _ in range(degree):
            if flat >= total:
                return edges
            target = targets[flat]
            flat += 1
            if target != source and target < count:
                edges.add((min(source, target), max(source, target)))
    return edges


def pathgrid_records(records, ctx) -> list:
    """Every TES4 PGRD this plugin's Morrowind pathgrids become.

    An interior keeps its single graph whole. Exteriors are bucketed into the
    Oblivion quadrants their points fall in and merged there: two Morrowind
    cells can reach into one quadrant, and a cell holds only one navmesh.

    An exterior pathgrid carries a NAME too -- often a REGION rather than a
    cell -- so the name cannot say which this is. The DATA grid can, and is
    what xEdit keys its own grid-cell callback on.
    """
    out, quads = [], {}
    for rec in records:
        parsed = parse_pathgrid(rec)
        if parsed is None:
            continue
        grid, points, edges = parsed
        if len(points) > MAX_TES4_POINT:
            continue
        if _is_interior(grid, rec.record_id, ctx):
            out.extend(_interior_records(rec.record_id, points, edges, ctx))
        else:
            _bucket_quadrants(grid, points, edges, ctx, quads)
    for quad in sorted(quads):
        record = _quadrant_record(quad, quads[quad], ctx)
        if record is not None:
            out.append(record)
    return out


class _Quadrant:
    """One Oblivion cell's accumulated points, edges and crossings."""

    def __init__(self):
        """An empty quadrant, before any cell has contributed to it."""
        self.points = []
        self.edges = set()
        self.crossings = []

    def add(self, point: tuple) -> int:
        """Append a point; return the slot it took."""
        self.points.append(point)
        return len(self.points) - 1


def _bucket_quadrants(grid: tuple, points: list, edges: set, ctx,
                      quads: dict) -> None:
    """Fold one exterior pathgrid into the per-quadrant accumulator.

    Point indices are rebased onto each quadrant's own running list as they
    are added, so edges stay meaningful once several cells have contributed.
    """
    world = _to_world(grid, points)
    owned = set(tes3_cell_quadrants(*grid))
    slots = {}
    for index, point in enumerate(world):
        quad = cell_grid(point[0], point[1])
        if quad not in owned and not _claimed(quad, ctx):
            continue
        held = quads.setdefault(quad, _Quadrant())
        slots[index] = (quad, held.add(point))
    for low, high in edges:
        _place_edge(low, high, slots, quads, world)


def _place_edge(low: int, high: int, slots: dict, quads: dict,
                world: list) -> None:
    """Keep one edge, as an edge within a quadrant or a crossing between two.

    A crossing is recorded on each side as (local slot, foreign position), so
    both cells learn where the path leaves them.
    """
    left, right = slots.get(low), slots.get(high)
    if left is None or right is None:
        return
    if left[0] == right[0]:
        quads[left[0]].edges.add((min(left[1], right[1]),
                                  max(left[1], right[1])))
        return
    quads[left[0]].crossings.append((left[1], world[high]))
    quads[right[0]].crossings.append((right[1], world[low]))


def _is_interior(grid: tuple, name: str, ctx) -> bool:
    """Whether this pathgrid belongs to an interior cell.

    An interior has no grid to record, so it leaves DATA at the origin --
    measured over TR_Mainland.esm, all 2930 interior pathgrids sit at (0, 0)
    and all 506 exterior ones carry a non-zero grid. Only the origin square
    itself is ambiguous, and there the cell name settles it.
    See: docs/commentary/tes4_export_morrowind.md#pathgrids
    """
    if grid != (0, 0):
        return False
    if not name:
        return False
    return (name.lower() in ctx.interior_names
            or ctx.index.lookup_interior(name) is not None)


def _interior_records(name: str, points: list, edges: set, ctx) -> list:
    """One PGRD for an interior cell, whose graph never splits."""
    if len(points) < MIN_POINTS:
        return []
    lines = _point_lines(points, _adjacency(edges, len(points)))
    return [(ctx.derive('pgrd:%s' % name.lower()),
             ['RecordFlags=0', f'ParentCELL={ctx.interior_cell_id(name)}']
             + lines)]


def _to_world(grid: tuple, points: list) -> list:
    """Cell-local exterior points moved into world space.

    See: docs/commentary/tes4_export_morrowind.md#pathgrids
    """
    origin_x = grid[0] * TES3_CELL_SIZE
    origin_y = grid[1] * TES3_CELL_SIZE
    return [(x + origin_x, y + origin_y, z) for x, y, z in points]


def _claimed(quad: tuple, ctx) -> bool:
    """Whether a cell was written for this grid square, so a PGRD may name it."""
    return ctx.exterior_cell_id(quad) in ctx.exterior_cell_ids


def _quadrant_record(quad: tuple, held, ctx) -> tuple:
    """One quadrant's PGRD: its own points, plus crossings out of it."""
    order = _lead_with_an_edge(list(range(len(held.points))), held.edges)
    slot = {index: place for place, index in enumerate(order)}
    points = [held.points[index] for index in order]
    edges = {(min(slot[low], slot[high]), max(slot[low], slot[high]))
             for low, high in held.edges}
    crossings = [(slot[local], exit_at) for local, exit_at in held.crossings]
    if len(points) < MIN_POINTS and not crossings:
        return None
    lines = _point_lines(points, _adjacency(edges, len(points)))
    lines.extend(_intercell_lines(crossings))
    return (ctx.derive('pgrd:%d:%d' % quad),
            ['RecordFlags=262144', f'ParentWRLD={ctx.worldspace_id()}',
             f'ParentCELL={ctx.exterior_cell_id(quad)}'] + lines)


def _lead_with_an_edge(indices: list, edges: set) -> list:
    """`indices` reordered so a point keeping an in-cell edge comes first.

    The importer probes Point[0].Edge[0] alone and falls back to
    nearest-neighbour topology for the WHOLE record when it is missing, which
    splitting a cell can cause by turning point 0's every edge into a
    crossing. Order is otherwise ours to choose.
    See: docs/commentary/tes4_export_morrowind.md#pathgrids
    """
    here = set(indices)
    connected = set()
    for low, high in edges:
        if low in here and high in here:
            connected.add(low)
            connected.add(high)
    for slot, index in enumerate(indices):
        if index in connected:
            return indices[slot:] + indices[:slot]
    return indices


def _adjacency(edges, count: int) -> list:
    """Each point's neighbour slots, ascending, as an undirected graph."""
    out = [[] for _ in range(count)]
    for low, high in sorted(edges):
        out[low].append(high)
        out[high].append(low)
    return out


def _point_lines(points: list, adjacency: list) -> list:
    """DATA.PointCount, every point, then every edge.

    A point's Connections count IS the edge loop bound the importer reads, so
    the two must agree exactly.
    """
    lines = ['DATA.PointCount=%d' % len(points)]
    for index, (x, y, z) in enumerate(points):
        lines.extend([f'Point[{index}].X={_f32(x)}',
                      f'Point[{index}].Y={_f32(y)}',
                      f'Point[{index}].Z={_f32(z)}',
                      f'Point[{index}].Connections={len(adjacency[index])}'])
    for index, neighbours in enumerate(adjacency):
        for slot, target in enumerate(neighbours):
            lines.append(f'Point[{index}].Edge[{slot}]={target}')
    return lines


def _intercell_lines(crossings: list) -> list:
    """PGRI entries: a local point and the world position it exits toward."""
    if not crossings:
        return []
    lines = ['InterCellCount=%d' % len(crossings)]
    for slot, (local_point, (x, y, z)) in enumerate(crossings):
        lines.extend([f'InterCell[{slot}].LocalPoint={local_point}',
                      f'InterCell[{slot}].X={_f32(x)}',
                      f'InterCell[{slot}].Y={_f32(y)}',
                      f'InterCell[{slot}].Z={_f32(z)}'])
    return lines


def _f32(value: float) -> float:
    """A float rounded to the float32 the TES4 exporter would have written."""
    return struct.unpack('<f', struct.pack('<f', value))[0]
