"""Generate the FO3/FNV -> TES5 condition-function index table from xEdit source.

FO3/FNV number their condition functions differently from Skyrim once the two
tables diverge: 58 functions keep their name but move slot, and 237 exist only
in Fallout. Joining the two `wbConditionFunctions` arrays BY NAME gives the
slot a Fallout CTDA must be rewritten to, and the set that has no Skyrim
function at all (including slots Skyrim reuses for a different function,
which pass-through would silently invoke).

Usage:
    python tools/generators/gen_ctda_fnv_remap.py \\
        references/xEdit/Core/wbDefinitionsFNV.pas \\
        references/xEdit/Core/wbDefinitionsTES5.pas \\
        -o tes5_import/generated/ctda_fnv_remap.py
"""
import argparse

from gen_ctda_param_types import parse_functions


def build(fallout_pas: str, tes5_pas: str) -> tuple:
    """({fallout index: (tes5 index, name)} for moved names, [(index, name)] absent)."""
    fallout = parse_functions(open(fallout_pas, encoding='utf-8',
                                   errors='replace').read())
    tes5 = parse_functions(open(tes5_pas, encoding='utf-8',
                                errors='replace').read())
    by_name = {name: idx for idx, (name, _p) in tes5.items()}
    moved, absent = {}, []
    for idx, (name, _p) in sorted(fallout.items()):
        target = by_name.get(name)
        if target is None:
            absent.append((idx, name))
        elif target != idx:
            moved[idx] = (target, name)
    return moved, absent


def emit(moved: dict, absent: list, sources: str) -> str:
    """Render the generated Python module."""
    lines = [
        '"""FO3/FNV condition-function index reconciliation (GENERATED — do not edit).',
        '',
        f'Generated by tools/generators/gen_ctda_fnv_remap.py from {sources}.',
        '',
        'FNV_FUNC_REMAP: Fallout index -> Skyrim index for a function both games',
        'name identically but number differently. FNV_FUNC_ABSENT: Fallout',
        'indices Skyrim has no function for (a reused slot counts as absent).',
        'Same-name same-index functions are omitted: they pass through unchanged.',
        '"""',
        '',
        'FNV_FUNC_REMAP = {',
    ]
    for idx, (target, name) in sorted(moved.items()):
        lines.append(f'    {idx}: {target},  # {name}')
    lines += ['}', '', 'FNV_FUNC_ABSENT = frozenset({']
    for idx, name in absent:
        lines.append(f'    {idx},  # {name}')
    lines += ['})', '']
    return '\n'.join(lines)


def main():
    """Parse the two xEdit tables and write (or print) the generated module."""
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('fallout_pas', help='path to wbDefinitionsFNV.pas (or FO3)')
    ap.add_argument('tes5_pas', help='path to wbDefinitionsTES5.pas')
    ap.add_argument('-o', '--out', help='write the generated module here')
    args = ap.parse_args()
    moved, absent = build(args.fallout_pas, args.tes5_pas)
    sources = ' and '.join(p.replace(chr(92), '/')
                           for p in (args.fallout_pas, args.tes5_pas))
    text = emit(moved, absent, sources)
    if args.out:
        with open(args.out, 'w', encoding='utf-8', newline='\n') as fh:
            fh.write(text)
        print(f'wrote {args.out}: {len(moved)} moved, {len(absent)} absent')
    else:
        print(text)


if __name__ == '__main__':
    main()
