"""Names a converted script may not reuse: Papyrus keywords and every shipped script.

The compiler rejects a variable or property named the same as ANY script it
can see, and every later use of that name fails with it.  Oblivion EditorIDs
collide freely (`Door`, `DarkBrotherhood`, `MS14`).  The list is checked in
(`papyrus_reserved.txt`, generated by tools/generators/gen_papyrus_reserved.py
from Data/Scripts.zip) so the conversion is reproducible.
"""

import functools
import os

#: Papyrus keywords; a property may not be named for one.
_PAPYRUS_KEYWORDS = frozenset({
    'self', 'parent', 'as', 'is', 'new', 'return', 'if', 'else', 'elseif',
    'endif', 'while', 'endwhile', 'function', 'endfunction', 'event',
    'endevent', 'property', 'endproperty', 'state', 'endstate', 'auto',
    'autoreadonly', 'import', 'extends', 'native', 'global', 'hidden',
    'conditional', 'int', 'float', 'bool', 'string', 'none', 'true', 'false',
    'length', 'scriptname', 'next',
})


def _load_papyrus_script_names() -> set:
    """Every script name Skyrim ships (types AND gameplay scripts), lowercased."""
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        'papyrus_reserved.txt')
    try:
        with open(path, encoding='utf-8') as f:
            return {ln.strip().lower() for ln in f
                    if ln.strip() and not ln.startswith('#')}
    except OSError:
        return set()


@functools.cache
def papyrus_reserved() -> frozenset:
    """Keywords plus every shipped script name; read on first use, not at import."""
    return _PAPYRUS_KEYWORDS | _load_papyrus_script_names()
