// GENERATED by tools/generators/gen_morrowind_chargen_swf.py.
// Edit the generator, not this file.

#pragma once

namespace tesruntime::mw::chargen_layout {

constexpr int kRowH = 18;
constexpr int kListRows = 7;

constexpr int kClassListViewX = 410;
constexpr int kClassListViewY = 218;
constexpr int kClassListViewW = 170;
constexpr int kClassListViewH = 130;
constexpr int kClassListScrollX = 582;
constexpr int kClassListScrollY = 218;
constexpr int kClassListScrollW = 14;
constexpr int kClassListScrollH = 130;
constexpr int kClassOkX = 809;
constexpr int kClassOkY = 482;
constexpr int kClassOkW = 64;
constexpr int kClassOkH = 24;
constexpr int kPick0X = 582;
constexpr int kPick0Y = 408;
constexpr int kPick0W = 140;
constexpr int kPick0H = 18;
constexpr int kPickColumnStep = 146;
constexpr int kPickPerColumn = 4;

constexpr int kBirthListViewX = 390;
constexpr int kBirthListViewY = 187;
constexpr int kBirthListViewW = 208;
constexpr int kBirthListViewH = 129;
constexpr int kBirthListScrollX = 600;
constexpr int kBirthListScrollY = 187;
constexpr int kBirthListScrollW = 14;
constexpr int kBirthListScrollH = 129;
constexpr int kBirthOkX = 829;
constexpr int kBirthOkY = 513;
constexpr int kBirthOkW = 64;
constexpr int kBirthOkH = 24;
constexpr int kBirthImageX = 628;
constexpr int kBirthImageY = 185;
constexpr int kBirthImageW = 259;
constexpr int kBirthImageH = 133;
constexpr int kBirthLine0X = 390;
constexpr int kBirthLine0Y = 339;
constexpr int kBirthLine0W = 475;
constexpr int kBirthLine0H = 18;
constexpr int kBirthLines = 9;
constexpr int kIconLeft = 4;
constexpr int kIconIndent = 24;
constexpr int kOffstage = 4000;

}  // namespace tesruntime::mw::chargen_layout
