// GENERATED by tools/disasm/pre_ae_map.py -- DO NOT EDIT.
// Each pre-AE build's address for an AE id, proven by an anchor and
// a shape check; an id with no proof is absent and stays unresolved.
// See: docs/reference/address_library_formats.md#pre-ae-tables

#pragma once

#include "addresses.h"

namespace tesruntime::pre_ae {

constexpr IdRva kBuild1597[] = {
    {13631, 0x1652d0},  // kUIAddMessage
    {40488, 0x6a2540},  // kPlayerAdvanceSkill
    {51740, 0x886a40},  // kGfxSetString
    {52518, 0x8c0b80},  // kPerksCanProcess
    {52662, 0x8ce590},  // kTrainingMenuTrainCaller
    {52667, 0x8ce8e0},  // kTrainingMenuTrain
    {53978, 0x927620},  // kVmMagicEffectApplyProcess
    {54675, 0x94aa70},  // kActorGetValue
    {54678, 0x94ac20},  // kActorGetBaseValue
    {54686, 0x94af60},  // kActorGetFactionRank
    {54743, 0x94c360},  // kActorSetValue
    {54750, 0x94c9c0},  // kActorSetFactionRank
    {54927, 0x958350},  // kActorGetLevel
    {54930, 0x958390},  // kActorGetRace
    {55377, 0x96ddb0},  // kDebugNotification
    {55465, 0x972e10},  // kGetFormFromFile
    {55469, 0x9731b0},  // kGameGetPlayer
    {55566, 0x9794b0},  // kGameGetForm
    {56632, 0x9ae930},  // kRefGetParentCell
    {68552, 0xc11f30},  // kControlMapAllowTextInput
    {69161, 0xc28bf0},  // kBSFixedStringCtor
    {69161, 0xc28bf0},  // kFixedStringCtor
    {82074, 0xebe150},  // kMenuManagerIsMenuOpen
    {82086, 0xebf9c0},  // kMenuManagerRegister
    {82270, 0xecb0e0},  // kGfxReleaseManaged
    {82325, 0xece790},  // kGFxLoaderLoadMovie
    {208040, 0x16635e0},  // kPlayerVtable
    {215975, 0x16bc168},  // kPerksHandlerVtable
    {217097, 0x16cdfd0},  // kVmMagicEffectApplySink
    {400327, 0x1ebeb20},  // kMenuManagerSingleton
    {400445, 0x1ec0a70},  // kUIManagerSingleton
    {400863, 0x2ec5bd0},  // kControlMapSingleton
    {402775, 0x2f257a0},  // kGFxLoaderSingleton
    {412058, 0x3032c50},  // kScaleformAllocator
};

constexpr IdRva kBuildVR[] = {
    {13631, 0x175a10},  // kUIAddMessage
    {40488, 0x6c30b0},  // kPlayerAdvanceSkill
    {51740, 0x53afd0},  // kGfxSetString
    {52662, 0x8fb660},  // kTrainingMenuTrainCaller
    {52667, 0x8fb9c0},  // kTrainingMenuTrain
    {53978, 0x962070},  // kVmMagicEffectApplyProcess
    {54675, 0x984e60},  // kActorGetValue
    {54678, 0x984f60},  // kActorGetBaseValue
    {54686, 0x985220},  // kActorGetFactionRank
    {54743, 0x9865d0},  // kActorSetValue
    {54750, 0x986c30},  // kActorSetFactionRank
    {54927, 0x9922d0},  // kActorGetLevel
    {54930, 0x992310},  // kActorGetRace
    {55377, 0x9a7e90},  // kDebugNotification
    {55465, 0x9acca0},  // kGetFormFromFile
    {55469, 0x9ad050},  // kGameGetPlayer
    {55566, 0x9b3b80},  // kGameGetForm
    {56632, 0x9e9460},  // kRefGetParentCell
    {68552, 0xc4e8d0},  // kControlMapAllowTextInput
    {69161, 0xc6db20},  // kBSFixedStringCtor
    {69161, 0xc6db20},  // kFixedStringCtor
    {82074, 0xf1a3b0},  // kMenuManagerIsMenuOpen
    {82086, 0xf1be20},  // kMenuManagerRegister
    {82325, 0xf2b480},  // kGFxLoaderLoadMovie
    {208040, 0x16e2230},  // kPlayerVtable
    {217097, 0x17564b8},  // kVmMagicEffectApplySink
    {400327, 0x1f83200},  // kMenuManagerSingleton
    {400445, 0x1f850f8},  // kUIManagerSingleton
    {400863, 0x2f8aaa0},  // kControlMapSingleton
    {402775, 0x2fea518},  // kGFxLoaderSingleton
    {412058, 0x318ce40},  // kScaleformAllocator
};

constexpr PreAeTable kTables[] = {
    {0x01050610, kBuild1597, sizeof(kBuild1597) / sizeof(kBuild1597[0])},
    {0x010400F0, kBuildVR, sizeof(kBuildVR) / sizeof(kBuildVR[0])},
};

}  // namespace tesruntime::pre_ae
