// GENERATED by tools/generators/gen_morrowind_stats_swf.py.
// Edit the generator, not this file.

#pragma once

namespace tesruntime::mw::stats_layout {

constexpr int kCaptionX = 394;
constexpr int kCaptionY = 193;
constexpr int kCaptionW = 492;
constexpr int kCaptionH = 20;
constexpr int kBarFill0X = 486;
constexpr int kBarFill0Y = 231;
constexpr int kBarFill0W = 126;
constexpr int kBarFill0H = 14;
constexpr int kBarFill1X = 486;
constexpr int kBarFill1Y = 249;
constexpr int kBarFill1W = 126;
constexpr int kBarFill1H = 14;
constexpr int kBarFill2X = 486;
constexpr int kBarFill2Y = 267;
constexpr int kBarFill2W = 126;
constexpr int kBarFill2H = 14;
constexpr int kSkillViewX = 630;
constexpr int kSkillViewY = 229;
constexpr int kSkillViewW = 224;
constexpr int kSkillViewH = 284;
constexpr int kSkillScrollX = 856;
constexpr int kSkillScrollY = 229;
constexpr int kSkillScrollW = 14;
constexpr int kSkillScrollH = 284;
constexpr int kAttrRowX = 410;
constexpr int kAttrRowY = 369;
constexpr int kAttrRowW = 204;
constexpr int kAttrRowH = 18;
constexpr int kCaptionPad = 8;
constexpr int kRowH = 18;
constexpr int kBarRows = 3;
constexpr int kInfoRows = 3;
constexpr int kAttributeRows = 8;
constexpr int kSkillFields = 16;

constexpr int kOkX = 786;
constexpr int kOkY = 574;
constexpr int kOkW = 64;
constexpr int kOkH = 24;
constexpr int kCoinRowX = 420;
constexpr int kCoinRowY = 458;
constexpr int kCoinRowW = 440;
constexpr int kCoinRowH = 16;
constexpr int kGridX = 462;
constexpr int kGridY = 482;
constexpr int kGridColumnStep = 186;
constexpr int kGridRowH = 20;
constexpr int kGridPerColumn = 4;
constexpr int kMultiplierW = 20;
constexpr int kNameW = 120;
constexpr int kCoin = 16;
constexpr int kCoinSpacing = 33;
constexpr int kCoins = 3;
constexpr const char* kClassImages[] = {"acrobat", "agent", "archer", "assassin", "barbarian", "bard", "battlemage", "crusader", "healer", "knight", "mage", "monk", "nightblade", "pilgrim", "rogue", "scout", "sorcerer", "spellsword", "thief", "warrior", "witchhunter"};
constexpr int kClassImageCount = 21;

constexpr int kStageW = 1280;
constexpr int kStageH = 720;
constexpr int kTipW = 320;
constexpr int kTipPad = 8;
constexpr int kTipTop = 48;
constexpr int kTipNameX = 48;
constexpr int kTipNameDy = 14;
constexpr int kTipSkillNameDy = 6;
constexpr int kTipAttrDy = 22;
constexpr int kTipGap = 2;
constexpr int kTipLabelH = 18;
constexpr int kTipLabelDy = -1;
constexpr int kTipBarW = 200;
constexpr int kTipBarH = 20;
constexpr int kTipBarTextDy = 0;
constexpr int kTipIcons = 8;
constexpr int kTipSkillFirst = 6;
constexpr int kTipSkillIcons = 18;

}  // namespace tesruntime::mw::stats_layout
